# Generated by Django 4.1.3 on 2022-11-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('conform_password', models.CharField(max_length=50)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'usermodel',
            },
        ),
    ]
