# Generated by Django 4.1.3 on 2022-11-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='conform_password',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='con_password',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
