# Generated by Django 4.1.3 on 2022-11-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentapp', '0002_remove_usermodel_conform_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='con_password',
        ),
    ]
